import { defineAction } from 'redux-define';

const REDUX_ACTION = ['REQUEST', 'SUCCESS', 'FAILURE'];

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  AUTH_LOGIN: defineAction('AUTH_LOGIN', REDUX_ACTION),
  AUTH_SIGNUP: defineAction('AUTH_SIGNUP', REDUX_ACTION),
  AUTH_LOGOUT: defineAction('AUTH_LOGOUT', REDUX_ACTION),
  AUTH_EMAIL_VERIFY: defineAction('AUTH_EMAIL_VERIFY', [
    'REQUEST',
    'SUCCESS',
    'FAILURE',
  ]),
  AUTH_FORGOT_PASSWORD: defineAction('AUTH_FORGOT_PASSWORD', REDUX_ACTION),
  AUTH_RESET_PASSWORD: defineAction('AUTH_RESET_PASSWORD', REDUX_ACTION),

  // Admin
  GET_USER_BY_ID: defineAction('GET_USER_BY_ID', REDUX_ACTION),
  UPDATE_TUTOR_HOURLY_RATE: defineAction(
    'UPDATE_TUTOR_HOURLY_RATE',
    REDUX_ACTION,
  ),

  CONIFIRM_REFERAL: defineAction('CONIFIRM_REFERAL', REDUX_ACTION),

  // User
  GET_USER: defineAction('GET_USER', REDUX_ACTION),
  UPLOAD_AVATAR: defineAction('UPLOAD_AVATAR', REDUX_ACTION),
  GET_AVATAR: defineAction('GET_AVATAR', REDUX_ACTION),
  UPDATE_USER: defineAction('UPDATE_USER', REDUX_ACTION),
  UPLOAD_PRESET: defineAction('UPLOAD_PRESET', REDUX_ACTION),

  // Students
  GET_STUDENT_INFO: defineAction('GET_STUDENT_INFO', REDUX_ACTION),
  FETCH_STUDENTS: defineAction('FETCH_STUDENTS', REDUX_ACTION),
  UPDATE_STUDENT_PROFILE: defineAction('UPDATE_STUDENT_PROFILE', REDUX_ACTION),
  GET_STUDENT_LIST: defineAction('GET_STUDENT_LIST', REDUX_ACTION),
  FETCH_FAVORITE_TUTORS: defineAction('FETCH_FAVORITE_TUTORS', REDUX_ACTION),
  SET_FAVOURITE: defineAction('SET_FAVOURITE', REDUX_ACTION),
  SET_REVIEW: defineAction('SET_REVIEW', REDUX_ACTION),
  SET_TUTOR_ATTENDANCE: defineAction('SET_TUTOR_ATTENDANCE', REDUX_ACTION),

  // Tutors
  GET_TUTOR_INFO: defineAction('GET_TUTOR_INFO', REDUX_ACTION),
  GET_TUTOR_LIST: defineAction('GET_TUTOR_LIST', REDUX_ACTION),
  GET_TUTOR_OVERALL_SUMMARY: defineAction(
    'GET_TUTOR_OVERALL_SUMMARY',
    REDUX_ACTION,
  ),
  GET_TUTOR_PAYMENT_HISTORY: defineAction(
    'GET_TUTOR_PAYMENT_HISTORY',
    REDUX_ACTION,
  ),
  FETCH_TUTORS: defineAction('FETCH_TUTORS', REDUX_ACTION),
  FETCH_TUTOR_RATES: defineAction('FETCH_TUTOR_RATES', REDUX_ACTION),
  UPDATE_TUTOR_INFO: defineAction('UPDATE_TUTOR_INFO', REDUX_ACTION),
  UPDATE_TUTOR_AVAILABILITIES: defineAction(
    'UPDATE_TUTOR_AVAILABILITIES',
    REDUX_ACTION,
  ),
  UPDATE_TUTOR_EXCEPTIONDATES: defineAction(
    'UPDATE_TUTOR_EXCEPTIONDATES',
    REDUX_ACTION,
  ),

  // Appointment
  CREATE_LESSON_EXIST: defineAction('CREATE_LESSON_EXIST', REDUX_ACTION),
  GET_APPOINTMENT_INFO: defineAction('GET_APPOINTMENT_INFO', REDUX_ACTION),
  CREATE_APPOINTMENT_INFO: defineAction(
    'CREATE_APPOINTMENT_INFO',
    REDUX_ACTION,
  ),
  APPROVE_APPOINTMENT_INFO: defineAction(
    'APPROVE_APPOINTMENT_INFO',
    REDUX_ACTION,
  ),
  CANCEL_APPOINTMENT_INFO: defineAction(
    'CANCEL_APPOINTMENT_INFO',
    REDUX_ACTION,
  ),
  UPDATE_APPOINTMENT_INFO: defineAction(
    'UPDATE_APPOINTMENT_INFO',
    REDUX_ACTION,
  ),

  // Message
  GET_MESSAGE_INFO: defineAction('GET_MESSAGE_INFO', REDUX_ACTION),

  // Subscription
  CREATE_PLAN: defineAction('CREATE_PLAN', REDUX_ACTION),
  UPDATE_PLAN: defineAction('UPDATE_PLAN', REDUX_ACTION),
  GET_PLAN: defineAction('GET_PLAN', REDUX_ACTION),
  GET_PLAN_STATUS: defineAction('GET_PLAN_STATUS', REDUX_ACTION),
  GET_SUBSCRIPTIONS: defineAction('GET_SUBSCRIPTIONS', REDUX_ACTION),

  DELETE_TUTOR: defineAction('DELETE_TUTOR', REDUX_ACTION),

  // Notification
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  READ_NOTIFICATION: 'READ_NOTIFICATION',
  DELETE_ALL_NOTIFICATION: 'DELETE_ALL_NOTIFICATION',
  CREATE_CANCELLATION: defineAction('CREATE_CANCELLATION', REDUX_ACTION),
};
