name: Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-22.04
    env:
      REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      REACT_APP_STRIPE_KEY: ${{ secrets.REACT_APP_STRIPE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Upload to bucket
        run: gcloud storage cp -r dist/** gs://dashboard-dev-naonow-com/

      - name: Invalidate cache
        run: gcloud compute url-maps invalidate-cdn-cache dashboard-dev-lb --path "/*" --async
