name: Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-24.04
    env:
      REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      REACT_APP_STRIPE_KEY: ${{ secrets.REACT_APP_STRIPE_KEY }}
      REACT_APP_PRODUCTION: ${{ secrets.REACT_APP_PRODUCTION }}
      REACT_APP_SERVER_WS_URL: ${{ secrets.REACT_APP_SERVER_WS_URL }}
      REACT_APP_KAKAO_APP_KEY: ${{ secrets.REACT_APP_KAKAO_APP_KEY }}
      REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload to bucket
        run: gcloud storage cp -r dist/** gs://dashboard-dev-naonow-com/

      - name: Invalidate cache
        run: gcloud compute url-maps invalidate-cdn-cache dashboard-dev-lb --path "/*" --async
