name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-22.04
    env:
      REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
      REACT_APP_STRIPE_KEY: ${{ secrets.REACT_APP_STRIPE_KEY }}
      REACT_APP_PORTONE_USER_CODE: ${{ secrets.REACT_APP_PORTONE_USER_CODE }}
      REACT_APP_PORTONE_MID: ${{ secrets.REACT_APP_PORTONE_MID }}
      REACT_APP_PRODUCTION: ${{ secrets.REACT_APP_PRODUCTION }}
      REACT_APP_SERVER_WS_URL: ${{ secrets.REACT_APP_SERVER_WS_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload to bucket
        run: gcloud storage cp -r dist/** gs://dashboard-naonow-com/

      - name: Invalidate cache
        run: gcloud compute url-maps invalidate-cdn-cache dashboard-prod-lb --path "/*" --async
